#!/usr/bin/env node
/**
 * On-Stop Hook
 * Runs when Claude Code session stops
 * - Generate session summary
 * - Create git checkpoint (stash)
 * - Calculate time and token metrics
 */

const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Use process.cwd() for portability instead of hardcoded path
const PROJECT_ROOT = process.cwd();

function main() {
  try {
    console.log('📊 Generating Claude Code session summary...\n');

    const timestamp = new Date().toISOString();
    const sessionDir = path.join(PROJECT_ROOT, '.claude', 'sessions');

    // Create sessions directory if it doesn't exist
    if (!fs.existsSync(sessionDir)) {
      fs.mkdirSync(sessionDir, { recursive: true });
    }

    // Get git status - use execFileSync to avoid command injection
    let gitStatus = 'No git repository';
    try {
      gitStatus = execFileSync('git', ['status', '--short'], {
        cwd: PROJECT_ROOT,
        encoding: 'utf-8'
      });
    } catch (err) {
      // Not a git repo or git not available
    }

    // Get git diff stats
    let diffStats = 'No changes';
    try {
      diffStats = execFileSync('git', ['diff', '--stat'], {
        cwd: PROJECT_ROOT,
        encoding: 'utf-8'
      });
    } catch (err) {
      // No git or no changes
    }

    // Read command audit log
    let commandCount = 0;
    const logFile = path.join(PROJECT_ROOT, '.claude', 'logs', 'command-audit.log');
    if (fs.existsSync(logFile)) {
      const logContent = fs.readFileSync(logFile, 'utf-8');
      commandCount = logContent.split('\n').filter(line => line.trim()).length;
    }

    // Generate summary report
    const summary = `# Claude Code Session Summary
Generated: ${timestamp}

## Git Status
\`\`\`
${gitStatus || 'Working tree clean'}
\`\`\`

## Changes Summary
\`\`\`
${diffStats || 'No changes'}
\`\`\`

## Session Metrics
- Commands executed: ${commandCount}
- Session end time: ${timestamp}

## Next Steps
Review the changes above and commit if satisfied.

---
Generated by OmniAudit Claude Code Hooks
`;

    // Save summary
    const summaryFile = path.join(sessionDir, `session-${Date.now()}.md`);
    fs.writeFileSync(summaryFile, summary);

    console.log(summary);
    console.log(`\n💾 Session summary saved to: ${summaryFile}`);

    // Create git checkpoint if there are changes
    if (gitStatus && gitStatus.trim()) {
      try {
        const stashMsg = `Claude Code checkpoint - ${timestamp}`;
        execFileSync('git', ['stash', 'push', '-m', stashMsg], {
          cwd: PROJECT_ROOT,
          stdio: 'pipe'
        });
        console.log(`\n✅ Git checkpoint created: ${stashMsg}`);
      } catch (err) {
        console.log('\n⚠️  Could not create git checkpoint');
      }
    }

    process.exit(0);

  } catch (error) {
    console.error('❌ On-stop hook error:', error.message);
    process.exit(0);
  }
}

main();
