#!/usr/bin/env node
/**
 * Pre-Write Hook
 * Validates file writes before they occur
 * - Blocks writes to sensitive files (.env*, *secret*, lockfiles unless allowed)
 * - Validates file extensions
 * - Checks disk space
 */

const fs = require('fs');
const path = require('path');

// Protected file patterns
const PROTECTED_PATTERNS = [
  /\.env/,
  /secret/i,
  /credential/i,
  /password/i,
  /\.key$/,
  /\.pem$/,
  /\.cert$/,
];

// Lockfiles (warn, but allow)
const LOCKFILE_PATTERNS = [
  /package-lock\.json$/,
  /pnpm-lock\.yaml$/,
  /yarn\.lock$/,
  /poetry\.lock$/,
  /Pipfile\.lock$/,
];

function main() {
  try {
    const args = process.argv.slice(2);
    const toolInput = args[0] ? JSON.parse(args[0]) : {};

    const filePath = toolInput.file_path || toolInput.path || '';

    if (!filePath) {
      console.log('✅ No file path detected, allowing operation');
      process.exit(0);
    }

    const fileName = path.basename(filePath);

    // Check protected patterns
    for (const pattern of PROTECTED_PATTERNS) {
      if (pattern.test(fileName) || pattern.test(filePath)) {
        console.error(`❌ BLOCKED: Cannot write to protected file: ${fileName}`);
        console.error('Protected files include: .env*, *secret*, *credential*, *.key, *.pem, *.cert');
        console.error('To override, use --dangerously-skip-permissions flag');
        process.exit(1);
      }
    }

    // Warn on lockfile changes
    for (const pattern of LOCKFILE_PATTERNS) {
      if (pattern.test(fileName)) {
        console.warn(`⚠️  WARNING: Modifying lockfile: ${fileName}`);
        console.warn('Ensure this is intentional. Lockfiles should typically be generated by package managers.');
        // Allow but warn
        break;
      }
    }

    // Check disk space (simplified - would be more robust in production)
    try {
      const stats = fs.statSync('/home/user/OmniAudit');
      // If we can stat the directory, assume we have space
      // In production, use proper disk space checking
    } catch (err) {
      console.warn('⚠️  Could not check disk space');
    }

    console.log(`✅ Write validated: ${fileName}`);
    process.exit(0);

  } catch (error) {
    console.error('❌ Pre-write hook error:', error.message);
    // On error, allow the operation but log the issue
    process.exit(0);
  }
}

main();
